# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4243430fe38053d72e16b6db2fc721ed95c6c449a22d9eb319e95b67cfe99d8070c320517efe2245fa66a96cf967f59c318c233155d5d8804d1484935b5e0fa

test:
  secret_key_base: dfd35a24840231f3c12225aa4e16d2be97c03d03a1a91046e323dedec4eab59fa8979033d69640fd4a66886a2c29ad7b4694627a6c7e76f4f67d728e1c410c58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
